# Generated by Django 4.1 on 2022-08-13 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
